
name: Build and Zip C++ Project

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
    - name: Build C++ Project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: Zip Executables
      run: |
        mkdir result
        cp build/pdftozip.exe result/
        cp pdftopng.exe result/
        cp zip.ps1 result/
        Compress-Archive -Path zip/* -DestinationPath result.zip
      shell: powershell
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Executables
        path: result.zip
